name: deploy
on:
    workflow_dispatch:
    workflow_run:
        workflows: [ "build" ]
        types: [ success ]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy to camelot
              uses: appleboy/ssh-action@v1
              with:
                host: 45.55.60.192
                username: root
                key: ${{ secrets.CAMELOT_PRIVATE_KEY }}
                port: 22
                script: |
                    cd pt-poosd
                    git pull
                    ./deploy.bash
